-- 코드를 입력하세요
SELECT *
FROM BOOK
WHERE
    CATEGORY = '경제';

SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR
INNER JOIN BOOK
    ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
WHERE
    CATEGORY = '경제'
ORDER BY
    PUBLISHED_DATE;